### ISSUE TITLE
UAA application seems like not accessible over the browser. I am getting "failure" white page

### ISSUE THREAD

**Issue by saratkumar123** [starkandwayne/uaa-deployment-cf#6]
Hi QUAA team @drnic @tpoland @krutten @jhunt @rkoster 

I have deployed QUAA on our OpenCF platform using the below document 
https://github.com/starkandwayne/quick-uaa-deployment-cf

After **quaa up --route subdomainname.mydoaminname.com** command the UAA application started running on the platform with the route but when I try accessing the endpoint over internet I see a white blank page with **"failure"** message. 

Also, when i do **quaa auth-client**  I get the below error logs.

![image](https://user-images.githubusercontent.com/56149476/105316862-79903900-5be7-11eb-8e13-9444620bd89e.png)

![image](https://user-images.githubusercontent.com/56149476/105317051-c247f200-5be7-11eb-8e9e-e4a41e1f9b8a.png)

**Comment by ravindraP20** [comment]
Please see the UAA log below:

   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT [CONTAINER] .ContainerBase.[Catalina].[localhost].[/].[spring] SEVERE  Servlet.service() for servlet [spring] in context with path [] threw exception
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener or DispatcherServlet registered?
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2021-01-27T07:36:48.29+0000 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2021-01-27T07:36:48.29+0000 [RTR/0] OUT uaa-elsa.elsabytjc.com - [2021-01-27T07:36:48.287+0000] "GET / HTTP/1.1" 503 0 7 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "10.0.1.4:57838" "10.0.16.15:61006" x_forwarded_for:"49.37.159.240:60028, 10.0.1.4" x_forwarded_proto:"http" vcap_request_id:"b9c8acde-af22-4144-5cdb-351d9a3d36cd" response_time:0.007478166 app_id:"991393dc-0edc-4c42-8bdf-bcb0c90b9d95" app_index:"0" x_b3_traceid:"75612c9e06d24b1d" x_b3_spanid:"75612c9e06d24b1d" x_b3_parentspanid:"-"
   2021-01-27T07:36:48.29+0000 [RTR/0] OUT
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT [CONTAINER] .ContainerBase.[Catalina].[localhost].[/].[spring] SEVERE  Servlet.service() for servlet [spring] in context with path [] threw exception
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener or DispatcherServlet registered?
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2021-01-27T07:36:48.55+0000 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2021-01-27T07:36:48.55+0000 [RTR/0] OUT uaa-elsa.elsabytjc.com - [2021-01-27T07:36:48.545+0000] "GET /favicon.ico HTTP/1.1" 503 0 7 "http://uaa-elsa.elsabytjc.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "10.0.1.4:57838" "10.0.16.15:61006" x_forwarded_for:"49.37.159.240:60028, 10.0.1.4" x_forwarded_proto:"http" vcap_request_id:"9e2b20d8-cb01-484c-7943-4a387e82923e" response_time:0.006591622 app_id:"991393dc-0edc-4c42-8bdf-bcb0c90b9d95" app_index:"0" x_b3_traceid:"5cb15e35648eafa2" x_b3_spanid:"5cb15e35648eafa2" x_b3_parentspanid:"-"
   2021-01-27T07:36:48.55+0000 [RTR/0] OUT
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT [CONTAINER] .ContainerBase.[Catalina].[localhost].[/].[spring] SEVERE  Servlet.service() for servlet [spring] in context with path [] threw exception
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener or DispatcherServlet registered?
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2021-01-27T07:37:03.49+0000 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2021-01-27T07:37:03.49+0000 [RTR/0] OUT uaa-elsa.elsabytjc.com - [2021-01-27T07:37:03.489+0000] "GET / HTTP/1.1" 503 0 7 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "10.0.1.5:58728" "10.0.16.15:61006" x_forwarded_for:"49.37.159.240:60029, 10.0.1.5" x_forwarded_proto:"https" vcap_request_id:"62ad1966-6e42-4b2f-78c9-1463f25befd1" response_time:0.008979739 app_id:"991393dc-0edc-4c42-8bdf-bcb0c90b9d95" app_index:"0" x_b3_traceid:"b4b86a5729df5fd2" x_b3_spanid:"b4b86a5729df5fd2" x_b3_parentspanid:"-"
   2021-01-27T07:37:03.49+0000 [RTR/0] OUT
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT [CONTAINER] .ContainerBase.[Catalina].[localhost].[/].[spring] SEVERE  Servlet.service() for servlet [spring] in context with path [] threw exception
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener or DispatcherServlet registered?
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2021-01-27T07:37:03.75+0000 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2021-01-27T07:37:03.75+0000 [RTR/0] OUT uaa-elsa.elsabytjc.com - [2021-01-27T07:37:03.745+0000] "GET /favicon.ico HTTP/1.1" 503 0 7 "https://uaa-elsa.elsabytjc.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "10.0.1.5:58728" "10.0.16.15:61006" x_forwarded_for:"49.37.159.240:60029, 10.0.1.5" x_forwarded_proto:"https" vcap_request_id:"1b835a78-529b-4942-6aec-e74a879f71de" response_time:0.008493416 app_id:"991393dc-0edc-4c42-8bdf-bcb0c90b9d95" app_index:"0" x_b3_traceid:"26be236480cd07fc" x_b3_spanid:"26be236480cd07fc" x_b3_parentspanid:"-"
   2021-01-27T07:37:03.75+0000 [RTR/0] OUT
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT [CONTAINER] .ContainerBase.[Catalina].[localhost].[/].[spring] SEVERE  Servlet.service() for servlet [spring] in context with path [] threw exception
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener or DispatcherServlet registered?
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2021-01-27T10:45:56.65+0000 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2021-01-27T10:45:56.65+0000 [RTR/0] OUT uaa-elsa.elsabytjc.com - [2021-01-27T10:45:56.652+0000] "GET /login HTTP/1.1" 503 0 7 "-" "curl/7.47.0" "10.0.1.4:59142" "10.0.16.15:61006" x_forwarded_for:"20.188.58.92:52698, 10.0.1.4" x_forwarded_proto:"http" vcap_request_id:"8b2cc896-e4d7-4e21-6ac0-fc1d2cb17203" response_time:0.007396263 app_id:"991393dc-0edc-4c42-8bdf-bcb0c90b9d95" app_index:"0" x_b3_traceid:"395f8290a15b0cdc" x_b3_spanid:"395f8290a15b0cdc" x_b3_parentspanid:"-"
   2021-01-27T10:45:56.65+0000 [RTR/0] OUT
