### ISSUE TITLE
error java.sql.SQLInvalidAuthorizationSpecException: SSL connection is required. Please specify SSL options and retry.

### ISSUE THREAD

**Issue by bhadana-rajesh** [starkandwayne/uaa-deployment-cf#7]
Hi, @starkandwayne-bot , @drnic 

I am using Azure Service Broker's MySql service 

After deployment of quaa with mysql , i am getting  java.sql.SQLInvalidAuthorizationSpecExceptio exception.

How can I configure SSL certificate for quaa ? if you can provide steps or guide me how to resolve the ssl error. 

2021-02-11T12:00:45.33+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.tomcat.jdbc.pool.ConnectionPool         WARNING initialSize is larger than maxActive, setting initialSize to: 4
   2021-02-11T12:00:45.65+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.tomcat.jdbc.pool.ConnectionPool         SEVERE  Unable to create initial connections of pool.
   **2021-02-11T12:00:45.65+0000 [APP/PROC/WEB/0] OUT java.sql.SQLInvalidAuthorizationSpecException: SSL connection is required. Please specify SSL options and retry.**
   2021-02-11T12:00:45.65+0000 [APP/PROC/WEB/0] OUT     at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:173)
   2021-02-11T12:00:45.65+0000 [APP/PROC/WEB/0] OUT     at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
   2021-02-11T12:00:45.65+0000 [APP/PROC/WEB/0] OUT     at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1

Thanks,
Rajesh

**Comment by drnic** [comment]
I'd suggest asking the UAA team for help debugging the UAA. You can find them on `#uaa` channel on CF Slack.

**Comment by bhadana-rajesh** [comment]
Hi @drnic ,

How can I add/install database SSL certificate along with quaa deployment. is there any configuration file  where I can add my db SSL certificate.

Thanks,
Rajesh
